name: 'Prerolls'
guid: '40ebce45-fe78-4e84-b819-3a9f537da73c'
version: '1.4.1.1'
targetAbi: '10.8.0.0'
framework: 'net6.0'
owner: 'clsop'
overview: 'Display flashy prerolls before movies and other videos'
description: >
  Select a flashy pre-roll from prerolls.video to run before any
  video content. The videos will be cached locally when selected
  to avoid buffering. After a new video is selected, the first
  playback event will take anywhere from 10 to 40 seconds to start
  while the pre-roll downloads.
category: 'Other'
artifacts:
- 'Jellyfin.Plugin.Prerolls.dll'
changelog: >
  Initial Release
  Preroll by genre
