name: release
jobs:
  test:
    on: push
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Runtime
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Dependencies
      run: dotnet restore
    - name: Test
      run: dotnet test
  publish:
    #if: startsWith(github.ref, 'refs/tags')
    on:
      push: tags
    runs-on: ubuntu-latest
    steps:
    - name: Repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Variables
      id: variables
      run: echo ::set-output name=version::$(git describe --tags --always)
    - name: Runtime
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration release
    - name: Move
      run: mv Jellyfin.Plugin.Prerolls/bin/*/*/Jellyfin.Plugin.Prerolls.dll .
    - name: Compress
      env:
        version: ${{ steps.variables.outputs.version }}
      run: zip jellyfin-plugin-prerolls-${version}.zip *.dll
    - name: Publish
      uses: ncipollo/release-action@v1
      with:
        artifacts: '*.zip'
        artifactContentType: zip
        tag: ${{ steps.variables.outputs.version }}
        commit: ${{ github.sha }}
        token: ${{ github.token }}
        bodyFile: CHANGES
